name: Easy_Gamemode_sign
author: Tallerik
description: Setzte ein Schild und schreib in die erste Zeile [gm] und in die zweite Survival oder Creative
version: 1.0.0

main: me.Tallerik.EGSignPlugin.EGSignPlugin

commands:
